### ISSUE TITLE
Encoding für Windows Systeme

### ISSUE THREAD

**Issue by StefanHol** [pinae/recipePDFtests#1]
Nach dem Laden der JSON-Datei werden unter Windows die Zeichen mit Umlauten fehlerhaft dargestellt.

Dies ist einfach zu beheben, wenn das Encoding, beim Ladan der Datei, angegeben wird.
`with open("recipes.json", 'r', encoding='utf8') as json_file:`

Diese Änderung sollte unter Linux keinen Einfluss haben.

**Comment by pinae** [comment]
Danke für den Hinweis! Ich habe den Code im Jupyter Notebook entsprechend angepasst.
